import Head from 'next/head'
import Banner from '../components/Banner';
import Header from "../components/Header";
import Productfeed from '../components/Productfeed';


export default function Home({ product }) {
  return (
    <div className="bg-gray-200">
      <Head>
        <title>joseph website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       {/*Header*/}
           <Header />
         <main className="max-w-screen-2xl mx-auto">
           {/* bannersection */}
           <Banner/>

           {/* productsection */}
           <Productfeed product={product}/>
         </main>
     
    </div>
  )
}
export async function getServerSideProps(context) {
  const product = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
    product,
  },
  }
}
